In [4]:
import pandas as pd
import numpy as np

In [5]:
a = np.matrix([[1,2,3],[8,2,3],[0, 0, 1]])

In [6]:
b = a

In [7]:
b[2]=0

In [8]:
b

matrix([[1, 2, 3],
        [8, 2, 3],
        [0, 0, 0]])

In [9]:
a

matrix([[1, 2, 3],
        [8, 2, 3],
        [0, 0, 0]])

In [10]:
a*b

matrix([[17,  6,  9],
        [24, 20, 30],
        [ 0,  0,  0]])

In [11]:
a = a.T

In [12]:
a

matrix([[1, 8, 0],
        [2, 2, 0],
        [3, 3, 0]])

In [13]:
b

matrix([[1, 2, 3],
        [8, 2, 3],
        [0, 0, 0]])

In [14]:
a*b

matrix([[65, 18, 27],
        [18,  8, 12],
        [27, 12, 18]])

In [15]:
a[2][0]=1

In [16]:
a

matrix([[1, 8, 0],
        [2, 2, 0],
        [1, 1, 1]])

In [18]:
np.linalg.matrix_rank(a)

3