In [4]:
import numpy as np

In [6]:
a = np.array([1,2,3])

In [8]:
type(a)

numpy.ndarray

In [9]:
type([1,2,3])

list

In [10]:
a.shape

(3,)

In [11]:
b = np.array([[1,2,3],[4,5,6]])

In [12]:
b.shape

(2, 3)

In [13]:
a

array([1, 2, 3])

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
b.dtype

dtype('int64')

In [16]:
type(a)

numpy.ndarray

In [17]:
type(b)

numpy.ndarray

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(10,12)

array([10, 11])

In [26]:
c = range(10000)

In [27]:
c

range(0, 10000)

In [32]:
%timeit [i**3 for i in c]

3.89 ms ± 32.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [29]:
c_numpy = np.arange(10000)

In [31]:
%timeit c_numpy**3

25.9 µs ± 233 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [33]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]

In [34]:
%timeit list(map(lambda x,y: x*y, l1, l2))

1.23 ms ± 4.88 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [35]:
a1 = np.array(l1)
b1 = np.array(l2)

In [36]:
%timeit a1*b1

5.44 µs ± 7.38 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [41]:
np.arange(2,40,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38])

In [42]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones((1,3))

array([[1., 1., 1.]])

In [47]:
np.diag((3,4))

array([[3, 0],
       [0, 4]])

In [48]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [51]:
np.full((3,3), 2.2, dtype=int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [52]:
v = np.array([1,2,3])

In [53]:
v

array([1, 2, 3])

In [56]:
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [61]:
50*np.random.random()+2

35.06783612904081

In [64]:
np.random.random((3,3))

array([[0.81805236, 0.90307501, 0.95297547],
       [0.164721  , 0.15236174, 0.20325433],
       [0.25729661, 0.15925172, 0.91431437]])