In [1]:
import numpy as np

In [2]:
a = np.linspace(1,50,100)

In [6]:
a.itemsize
#number of bytes stored

8

In [10]:
b = np.arange(18).reshape(2,3,3)
# 3x3 matrix 2 times a 3d matrix

In [11]:
b.shape

(2, 3, 3)

In [14]:
np.arange(24).reshape(2,3,-1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
a = np.array([2,4,6,8,10])

In [17]:
a[0]

2

In [18]:
a[3]

8

In [22]:
a[[2,4]]

array([ 6, 10])

In [23]:
a[2:]

array([ 6,  8, 10])

In [24]:
a[:2]

array([2, 4])

In [27]:
a[-3:]

array([ 6,  8, 10])

In [28]:
a[::2]

array([ 2,  6, 10])

In [29]:
b = np.array([[2,3,4],[7,3,1]])

In [30]:
b

array([[2, 3, 4],
       [7, 3, 1]])

In [31]:
b[0][2]

4

In [32]:
b[0,2]

4

In [33]:
a>2

array([False,  True,  True,  True,  True])

In [34]:
b>2

array([[False,  True,  True],
       [ True,  True, False]])

In [36]:
b[(b>2)&(b<5)]

array([3, 4, 3])

In [37]:
b[0]=11

In [38]:
b

array([[11, 11, 11],
       [ 7,  3,  1]])

In [39]:
np.shares_memory(a,b)

False

In [40]:
c = b

In [41]:
np.shares_memory(b,c)

True

In [42]:
a

array([ 2,  4,  6,  8, 10])

In [43]:
b

array([[11, 11, 11],
       [ 7,  3,  1]])

In [44]:
b.T

array([[11,  7],
       [11,  3],
       [11,  1]])

In [45]:
d = np.array([[7,8,9],[10,11,12]])

In [46]:
b

array([[11, 11, 11],
       [ 7,  3,  1]])

In [47]:
d

array([[ 7,  8,  9],
       [10, 11, 12]])

In [48]:
b==d

array([[False, False, False],
       [False, False, False]])

In [52]:
#if I want to vertically stack b and d then one can do that
np.vstack((b,d))

array([[11, 11, 11],
       [ 7,  3,  1],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
#this is horizontal stacking
np.hstack((b,d))

array([[11, 11, 11,  7,  8,  9],
       [ 7,  3,  1, 10, 11, 12]])

In [55]:
np.sin(b)

array([[-0.99999021, -0.99999021, -0.99999021],
       [ 0.6569866 ,  0.14112001,  0.84147098]])

In [56]:
np.sum(a)

30

In [57]:
np.median(a)

6.0

In [58]:
a

array([ 2,  4,  6,  8, 10])

In [59]:
np.mean(a)

6.0

In [61]:
a.std()

2.8284271247461903

In [62]:
a.mean()

6.0

In [80]:
h = [[3,4,2],[8,2,9],[0,3,5]]

In [86]:
h = np.array(h)

In [87]:
np.linalg.det(h)

-162.99999999999986

In [88]:
np.linalg.inv(h)

array([[ 0.10429448,  0.08588957, -0.19631902],
       [ 0.24539877, -0.09202454,  0.06748466],
       [-0.14723926,  0.05521472,  0.1595092 ]])

In [89]:
g = h.T

In [90]:
np.dot(g,h)

array([[ 73,  28,  78],
       [ 28,  29,  41],
       [ 78,  41, 110]])

In [91]:
a = np.array([1,1,0], dtype=bool)

In [92]:
b = np.array([1,0,1], dtype=bool)

In [93]:
np.logical_and(a,b)

array([ True, False, False])

In [94]:
np.logical_or(a,b)

array([ True,  True,  True])

In [95]:
a==a

array([ True,  True,  True])

In [96]:
np.all(a==b)

False

In [97]:
np.all(a==a)

True

In [98]:
a.sum()

2

In [99]:
b.sum()

2

In [101]:
a = np.array([[1,2],[3,4]])

In [102]:
a.sum()


10

In [103]:
a.sum(axis=1)

array([3, 7])

In [104]:
a.sum(axis=0)

array([4, 6])

In [105]:
a.argmax()

3

In [106]:
a.max()

4

In [107]:
#index of the max element
a.argmax()

3

In [108]:
a.shape

(2, 2)

In [113]:
a = np.arange(1,10)

In [114]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
a.shape

(9,)

In [117]:
a[:,np.newaxis].shape

(9, 1)

In [118]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [119]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])